### DISCUSSION TITLE
GUID and DateTime? checks in Validate method

### DISCUSSION THREAD

**Discussion by awdorrin** [christianhelle/apiclientcodegen#1084] [Q&A]
I am attempting to generate C# Client code using .net8.0 and an openapi.yml file using the openapi generator.
Since this is the first time doing this, I'm not sure if this is an issue with this tool, or the openapi generator itself.
But I am getting checks in the validation code that look like this:

```
 if (this.EntityUUID != null && this.EntityUUID.Length > 255)
 {
     yield return new ValidationResult("Invalid value for EntityUUID, length must be less than 255.", new [] { "EntityUUID" });
 }
 
if (this.VendorEffectiveStartDate != null && this.VendorEffectiveStartDate.Length > 19)
{
    yield return new ValidationResult("Invalid value for VendorEffectiveStartDate, length must be less than 19.", new [] { "VendorEffectiveStartDate" });
}
```

Now, I think this is a result of how the YML is being defined and a difference in format and type definitions, and how the generator is trying to convert to native formats (GUID, DateTime)

```
        entityUUID:
          format: uuid
          title: Entity UUID
          description: ""
          maxLength: 255
          type: string
          xml:
            attribute: true
          example: ""
          nullable: false

        vendorEffectiveStartDate:
          format: date-time
          title: vendorEffectiveStartDate
          maxLength: 19
          type: string
          example: 2024-02-07T00:00:00
          nullable: true
          x-sip: eo.hcm.ecfs.sip.lmpi.general
          x-label: Effective Start Date
          x-sap-source: VendorInfo.effectiveStartDate
          x-field-category: FIELD
```

I am assuming, I could do a simple .ToString() in front of the length check, but, since this is the first encounter with this, I am not entirely sure, and I have not found anything on my searching yet.

Thanks for any suggestions
